Repository SelfKeyFoundation/Identity-Wallet, pull requests merged in 2018-08, with the labels that each got.

#355 Fix/balance
  src/main/controllers/rpc-handler.js
  src/renderer/angular/classes/wallet.js
  src/renderer/angular/controllers/commons/dialogs/send-token-controller.js
Labels: Bug

#366 fix: downgrade node to version 8 so unit tests can work
  .circleci/config.yml
  .nvmrc
  appveyor.yml
  yarn.lock
Labels: Maintenance

#387 fix: timezone
  appveyor.yml
Labels: Maintenance

#394 fix(coverage): remove renderer from coverage report
  README.md
  jest.config.js
  package.json
  src/common/config.js
  src/common/fiatCurrency/index.js
  src/common/fiatCurrency/types.js
  src/common/locale/i18n/en.js
  src/common/locale/i18n/ge.js
  src/common/locale/index.js
  src/common/locale/types.js
  src/common/logger/index.js
  src/common/prices/index.js
  src/common/prices/types.js
  src/common/store/configure-store.js
  src/common/tokens/index.js
  src/common/tokens/types.js
  src/common/view-all-tokens/index.js
  src/common/view-all-tokens/types.js
  src/common/wallet-tokens/index.js
  src/common/wallet-tokens/types.js
  src/common/wallet/index.js
  src/common/wallet/types.js
  src/main/autoupdater.js
  src/main/context.js
  src/main/db/db.js
  src/main/db/test-db.js
  src/main/keystorage/index.js
  src/main/knexfile.js
  src/main/main.js
  src/main/menu.js
  src/main/migrations/20180508093508_init.js
  src/main/migrations/20180613110104_seed_upgrades.js
  src/main/migrations/20180620115500_tx_history_table-replace.js
  src/main/migrations/20180620185801_tokens_constraints.js
  src/main/migrations/20180627193100_wallet_settings_upgrade.js
  src/main/migrations/20180628203700_guide_settings_add_crash_report.js
  src/main/migrations/20180716131300_wallet_settings_drop_pre-tx-count.js
  src/main/migrations/20180726210124_clear_token_price.js
  src/main/migrations/20180730153100_wallet_settings_reset-tx-history-sync.js
  src/main/migrations/20180802104855_id-attribute-refactor.js
  src/main/migrations/20180814164223_id-attribute-schema.js
  src/main/preload.js
  src/main/rpc-handler.js
  src/main/seeds/init.js
Labels: Maintenance

#403 feat: add back button to exchanges list screen
  src/renderer/templates/member/marketplace/exchange-list.pug
  static/stylesheets/scss/views/member/marketplace/exchange-list.scss
Labels: Improvements

#404 feat: remove coming soon from exchange list
  src/renderer/templates/member/marketplace/exchange-list.pug
Labels: Improvements

#406 fix(migrations): fix document handling in attribute migrations
  src/main/identity/id-attribute-type-service.js
  src/main/migrations/20180802104855_id-attribute-refactor.js
Labels: Bug

#409 fix: marketplace styling and text typo
  src/renderer/react/marketplace/index.js
  src/renderer/templates/member/marketplace/marketplace.pug
  static/stylesheets/scss/main.scss
  static/stylesheets/scss/views/member/marketplace/marketplace.scss
Labels: Bug

#412 Feat/marketplace screen
  src/renderer/react/marketplace/index.js
  yarn.lock
Labels: Bug
