Repository SelfKeyFoundation/Identity-Wallet, pull requests merged in 2019-03, with the labels that each got.

#807 fix(custom-token): blockchain search and duplication validation
  src/renderer/crypto-manager/add-token-container.jsx
Labels: Bug

#809 feat(selfkey-id): update marketplace text and button
  src/renderer/selfkey-id/main/components/selfkey-id-overview.jsx
Labels: Improvements

#811 fix(authentication): fix error using keystore file & existing address
  src/renderer/wallet/unlock/existing-address.jsx
  src/renderer/wallet/unlock/index.jsx
  src/renderer/wallet/unlock/new-address.jsx
Labels: Bug

#824 fix(process-started): update link
  src/renderer/marketplace/incorporation/pay/process-started.jsx
Labels: Bug

#833 test: fix for win build another way to install gcloud sdk
  appveyor.yml
Labels: Maintenance

#837 fix(app-version): retrieve version from package.json
  src/renderer/wallet/main/sidebar.jsx
Labels: Bug

#876 fix(relying-party): clear session after a payment or application failure
  src/renderer/marketplace/incorporation/pay/process-started.jsx
  src/renderer/transaction/transaction-declined/containers/transaction-declined.js
  src/renderer/transaction/transaction-error/containers/transaction-error.js
  src/renderer/transaction/transaction-no-gas-error/containers/transaction-no-gas-error.js
  src/renderer/transaction/transaction-timeout/index.jsx
Labels: Bug

#924 fix(edit-information): add type field and normalized column headers
  src/renderer/selfkey-id/main/components/edit-attribute.jsx
  src/renderer/selfkey-id/main/components/selfkey-id-overview.jsx
Labels: Bug

#930 Feat/incorporation api improvements
  package.json
  src/renderer/marketplace/incorporation/common/country-info.jsx
  src/renderer/marketplace/incorporation/common/index.js
  src/renderer/marketplace/incorporation/common/program-price.jsx
  src/renderer/marketplace/incorporation/common/sanitize-airtable-html.js
  src/renderer/marketplace/incorporation/detail/index.jsx
  src/renderer/marketplace/incorporation/pay/checkout.jsx
  yarn.lock
Labels: Improvements

#927 fix(custom-token): add loading feature
  src/renderer/crypto-manager/add-token-container.jsx
Labels: Bug

#936 fix(create-attribute): disable html validation and format layout
  src/renderer/selfkey-id/main/components/create-attribute.jsx
Labels: Improvements

#938 feat(delete-attribute): update labels and format style
  src/renderer/selfkey-id/main/components/delete-attribute.jsx
  src/renderer/selfkey-id/main/containers/delete-attribute-popup.js
Labels: Improvements

#946 fix(custom-token): update loading control flag
  src/renderer/crypto-manager/add-token-container.jsx
Labels: Bug

#948 fix(edit-attribute): disable html validation
  src/renderer/selfkey-id/main/components/edit-attribute.jsx
Labels: Improvements

#949 fix(sidebar): update scrollbar and version
  package.json
  src/renderer/wallet/main/sidebar.jsx
Labels: Bug

#952 feat(existing-address): add selfkey-id nickname
  src/renderer/wallet/unlock/existing-address.jsx
Labels: Improvements

#958 fix(main-window): hide electron default menu
  src/main/main-window.js
Labels: Bug

#959 fix(selfkey-id): replace email validation
  src/renderer/selfkey-id/main/components/selfkey-id-create-form.jsx
Labels: Bug

#977 fix(trezor): adapt to firmware 1.8.0
  package.json
  yarn.lock
Labels: High Priority

#971 fix(custom-token): add token error message
  src/common/tokens/actions.js
  src/common/tokens/operations.js
  src/common/tokens/reducers.js
  src/common/tokens/selectors.js
  src/common/tokens/types.js
  src/renderer/crypto-manager/add-token-container.jsx
Labels: Bug

#979 fix(custom-token): update error message
  src/common/tokens/operations.js
  src/renderer/crypto-manager/add-token-container.jsx
Labels: Improvements

#987 fix(create-attribute): add option style (reflects only on Windows)
  src/renderer/selfkey-id/main/components/create-attribute.jsx
Labels: Bug
