Repository SelfKeyFoundation/Identity-Wallet, pull requests merged in 2019-04, with the labels that each got.

#1032 Incorporations schema changes and refactor
  src/common/config.js
  src/main/marketplace/incorporations-service.js
  src/renderer/marketplace/incorporation/detail/index.jsx
Labels: Improvements

#1022 fix(e2e-test): get e2e back to work
  .circleci/config.yml
  package.json
  src/renderer/address-book/main/index.jsx
  src/renderer/dashboard/index.jsx
  src/renderer/home/index.jsx
  src/renderer/selfkey-id/main/components/selfkey-id-create-about.jsx
  src/renderer/selfkey-id/main/components/selfkey-id-create-disclaimer.jsx
  src/renderer/selfkey-id/main/components/selfkey-id-create-form.jsx
  src/renderer/selfkey-id/main/components/selfkey-id-create.jsx
  src/renderer/selfkey-id/main/components/selfkey-id-overview.jsx
  src/renderer/settings/terms.jsx
  src/renderer/wallet/create/backup-address.jsx
  src/renderer/wallet/create/backup-pk.jsx
  src/renderer/wallet/create/index.jsx
  src/renderer/wallet/create/password/confirmation.jsx
  src/renderer/wallet/create/password/index.jsx
  src/renderer/wallet/main/sidebar.jsx
  src/renderer/wallet/main/toolbar.jsx
  src/renderer/wallet/unlock/index.jsx
  src/renderer/wallet/unlock/private-key.jsx
  test/config/config.js
  test/data/data.json
  test/e2e/address-book/add-address-book.feature
  test/e2e/address-book/add-address-book.steps.js
  test/e2e/address-book/common-steps.js
  test/e2e/address-book/delete-address-book.feature
  test/e2e/address-book/delete-address-book.steps.js
  test/e2e/address-book/edit-address-book.steps.js
  test/e2e/address-book/open-address-book.feature
  test/e2e/address-book/open-address-book.steps.js
  test/e2e/basic_id/basic_id.spec.js
  test/e2e/common/common-steps.js
  test/jest-setup-test-framework.js
  test/utils/tools.js
  yarn.lock
Labels: Technical-Debt

#1104 fix(my-crypto): fix crypto chart update function
  src/renderer/dashboard/crypto-chart-box.jsx
Labels: Bug
